image: python:latest

services: 
  - name: postgres:latest

test:
  script:
  - apt-get update
  - apt-get install python3 python3-venv python3-dev libpq-dev build-essential -yqq
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install --upgrade pip setuptools
  - pip3 install -r requirements.txt
